SELECT *
FROM OSSYS_USER
WHERE USERNAME = 'burt.wang'
SELECT *
FROM OSSYS_LOGIN_ATTEMPT
WHERE USERID = 197147

SELECT *
FROM OSUSR_8MG_LRSESSION


DROP TABLE IF EXISTS #TEMP_TIMECARD_APP

SELECT *
INTO #TEMP_TIMECARD_APP
FROM [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARD_T2197] TT
WHERE TT.[TIMECARDSTATUSID] = 6
  AND TT.[DATE] >= '2023-07-01'
  AND TT.[DATE] <= '2023-08-03'

CREATE UNIQUE CLUSTERED INDEX IX ON #TEMP_TIMECARD_APP ([ID])

SELECT DISTINCT 125948,
                T.[ID],
                T.[DATE],
                T.[DURATION],
                T.[FIRMUSERID],
                [DEV_PLATFORM].DBO.[OSSYS_USER_T2197].[ID],
                [DEV_PLATFORM].DBO.[OSSYS_USER_T2197].[NAME],
                T.[FIXEDFEEAMOUNT],
                T.[PROJECTID],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_CLIENT_T2197].[ID],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_CLIENT_T2197].[CLIENTNAME],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_PROJECT_T2197].[PROJECTNAME],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_PROJECT_T2197].[ISDEFAULT],
                T.[RATE],
                T.[TIMECARDSTATUSID],
                T.[TOTALAMOUNT],
                T.[NOTES],
                T.[BILLABLESTATUSID],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TASKCODE_T2197].[CODE],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TASKCODE_T2197].[DESCRIPTION],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_WORKSOLVPHASE_T2197].[NAME] WORKSOLVPHASENAME,
                [DEV_PLATFORM].DBO.[OSUSR_PIF_WORKSOLVTASK_T2197].[NAME]  WORKSOLVTASKNAME,
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[ID],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[APPROVALSTATUS],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[LEVEL],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[PRIVATECOMMENTS],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[PUBLICCOMMENTS],
                T.[LASTUPDATEDBY],
                T.[LASTUPDATEDDATE],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[LASTUPDATEDBY],
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[LASTUPDATEDDATE],
                0,
                1,
                0,
                0,
                [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[ISPROJECTAPPROVAL],
                COUNT(*) OVER ()
FROM #TEMP_TIMECARD_APP T
         INNER JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_PROJECT_T2197]
                    ON T.[PROJECTID] = [DEV_PLATFORM].DBO.[OSUSR_PIF_PROJECT_T2197].[ID]
         INNER JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_CLIENT_T2197]
                    ON [DEV_PLATFORM].DBO.[OSUSR_PIF_PROJECT_T2197].[CLIENTID] =
                       [DEV_PLATFORM].DBO.[OSUSR_PIF_CLIENT_T2197].[ID]
         INNER JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_FIRMUSER_T2197]
                    ON T.[FIRMUSERID] = [DEV_PLATFORM].DBO.[OSUSR_PIF_FIRMUSER_T2197].[ID]
         INNER JOIN [DEV_PLATFORM].DBO.[OSSYS_USER_T2197] ON [DEV_PLATFORM].DBO.[OSUSR_PIF_FIRMUSER_T2197].[USERID] =
                                                             [DEV_PLATFORM].DBO.[OSSYS_USER_T2197].[ID]
         INNER JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197]
                    ON T.[ID] = [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[TIMECARDID] AND
                       [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[APPROVER] = 125948 AND
                       [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[APPROVALSTATUS] = 3
         INNER JOIN (SELECT TC1.[ID] TIMECARDID, MAX(TCA1.[ID]) TIMECARDAPPROVALID
                     FROM [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARD_T2197] TC1
                              INNER JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197] TCA1
                                         ON TC1.[ID] = TCA1.[TIMECARDID] AND
                                            TC1.[TIMECARDSTATUSID] = 6
                     GROUP BY TC1.[ID]) REJECTEDTIMECARDS ON T.[ID] = REJECTEDTIMECARDS.TIMECARDID AND
                                                             [DEV_PLATFORM].DBO.[OSUSR_PIF_TIMECARDAPPROVAL_T2197].[ID] =
                                                             REJECTEDTIMECARDS.TIMECARDAPPROVALID
         LEFT JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_WORKSOLVTASK_T2197]
                   ON T.[WORKSOLVTASKID] = [DEV_PLATFORM].DBO.[OSUSR_PIF_WORKSOLVTASK_T2197].[ID]
         LEFT JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_WORKSOLVPHASE_T2197]
                   ON [DEV_PLATFORM].DBO.[OSUSR_PIF_WORKSOLVTASK_T2197].[WORKSOLVPHASEID] =
                      [DEV_PLATFORM].DBO.[OSUSR_PIF_WORKSOLVPHASE_T2197].[ID]
         LEFT JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_TASKCODE_T2197]
                   ON T.[TASKCODEID] = [DEV_PLATFORM].DBO.[OSUSR_PIF_TASKCODE_T2197].[ID]
         LEFT JOIN [DEV_PLATFORM].DBO.[OSUSR_PIF_SUBTASKCODE_T2197]
                   ON T.[SUBTASKCODEID] = [DEV_PLATFORM].DBO.[OSUSR_PIF_SUBTASKCODE_T2197].[ID]

ORDER BY T.[DATE] DESC
OFFSET 50 ROWS FETCH NEXT 50 ROWS ONLY