SELECT U.NAME, C.NAME, U.EMAIL AS MAP_EMAIL, U.USERNAME AS CRM_USERNAME, C.EMAIL AS CRM_EMAIL, U.EXTERNAL_ID, C.ID
FROM OSSYS_USER U
         INNER JOIN CRM.DBO.CONTACT C ON CAST(C.ID AS NVARCHAR(36)) COLLATE LATIN1_GENERAL_100_CI_AI_SC =
                                         U.EXTERNAL_ID COLLATE LATIN1_GENERAL_100_CI_AI_SC
WHERE U.EMAIL <> C.EMAIL COLLATE LATIN1_GENERAL_100_CI_AI_SC


-- from SBC_CleanupEmails script
-- UPDATE OUTSYSTEMS.[dbo].[ossys_User]
-- SET EMAIL    = C.EMAIL,
--     USERNAME = C.EMAIL
-- FROM OUTSYSTEMS.[dbo].[ossys_User] U
--          JOIN CRM.DBO.CONTACT C ON
--     U.EXTERNAL_ID = C.ID
-- WHERE U.EXTERNAL_ID LIKE '%-%-%-%'
--   AND ((U.EMAIL <> C.EMAIL COLLATE LATIN1_GENERAL_100_CI_AI_SC) OR
--        (U.USERNAME <> U.EMAIL COLLATE LATIN1_GENERAL_100_CI_AI_SC))