SELECT C.*
FROM COMPLETEDTABLE_4 C
         INNER JOIN COMPLETEDRESULTTABLE_3 R ON R.RECORDID = C.RECORDID
         INNER JOIN COMPLETEDPUBLISHTABLE_2 P ON P.RECORDID = R.RECORDID
WHERE C.SUBMITTER = 'TimeSolv\FirmUser158836'
ORDER BY C.RECORDID;


DELETE
FROM COMPLETEDRESULTTABLE_3
WHERE RECORDID IN (SELECT C.RECORDID
                   FROM COMPLETEDTABLE_4 C
                   WHERE C.SUBMITTER = 'TimeSolv\FirmUser158836'
                     )

DELETE
FROM COMPLETEDPUBLISHTABLE_2
WHERE RECORDID IN (SELECT C.RECORDID
                   FROM COMPLETEDTABLE_4 C
                   WHERE C.SUBMITTER = 'TimeSolv\FirmUser158836'
                     )


DELETE
FROM COMPLETEDTABLE_4
WHERE SUBMITTER = 'TimeSolv\FirmUser158836';

SELECT *
FROM COMPLETEDTABLE_4
WHERE SUBMITTER = 'TimeSolv\FirmUser158836'
  AND ISSUCCESSFUL = 0
