-- 24 month back
SELECT COUNT(*), DATEADD(YEAR, -2, GETDATE()) AS DATE_BEFORE
FROM OSUSR_GT6_FILECONTENT C
         INNER JOIN OSUSR_GT6_FILESTORE S ON S.FILECONTENTID = C.ID
WHERE S.CREATEDTIMESTAMP <= DATEADD(YEAR, -2, GETDATE())

--12 month back
SELECT COUNT(*)                                      AS ROWS,
       SUM(DATALENGTH(CONTENT)) / 1000 / 1000 / 1000 AS SIZE,
       DATEADD(YEAR, -2, GETDATE())                  AS DATE_FROM,
       DATEADD(YEAR, -1, GETDATE())                  AS DATE_TO
FROM OSUSR_GT6_FILECONTENT C
         INNER JOIN OSUSR_GT6_FILESTORE S
                    ON S.FILECONTENTID = C.ID
WHERE S.CREATEDTIMESTAMP <= DATEADD(YEAR, -1, GETDATE())
  AND S.CREATEDTIMESTAMP >= DATEADD(YEAR, -2, GETDATE())

--2023
SELECT SUM(DATALENGTH(CONTENT)) / 1000 / 1000 / 1000, DATEADD(MONTH, -12, GETDATE()) AS DATE_FROM
FROM OSUSR_GT6_FILECONTENT C
         INNER JOIN OSUSR_GT6_FILESTORE S ON S.FILECONTENTID = C.ID
WHERE S.CREATEDTIMESTAMP >= DATEADD(MONTH, -6, GETDATE())

SELECT COUNT(*) AS ROWS, SUM(DATALENGTH(CONTENT)) / 1000 / 1000 / 1000 AS SIZE_GB
FROM OSDATAARCHIVE.DBO.OSUSR_GT6_FILECONTENT

INSERT
INTO OSDATAARCHIVE.DBO.OSUSR_GT6_FILECONTENT
    WITH (TABLOCKX) (ID, CONTENT)
SELECT TOP (10) C.ID, C.CONTENT
FROM OSDATA.DBO.OSUSR_GT6_FILECONTENT C
         INNER JOIN OSDATA.DBO.OSUSR_GT6_FILESTORE S ON S.FILECONTENTID = C.ID
WHERE S.CREATEDTIMESTAMP <= DATEADD(YEAR, -2, GETDATE())
  AND NOT EXISTS(SELECT 1
                 FROM OSDATAARCHIVE.DBO.OSUSR_GT6_FILECONTENT DT
                 WHERE DT.ID = C.ID)
ORDER BY ID


SELECT DATEFROMPARTS(YEAR(GETDATE()) - 1, 1, 1) AS BEGINNINGOFLASTYEAR;

SELECT CONVERT(BINARY(1), 'a') AS BINARYVALUEOFA;

SELECT *
FROM OSDATAARCHIVE.DBO.OSUSR_GT6_FILECONTENT
WHERE ID = 11365