USE PRODUCTION;
DECLARE @FIRMUSERID INT = 67794;
DECLARE @STARTDATE DATE = NULL;
DECLARE @CLIENTSTATUSACTIVE INT = 2;
DECLARE @INCLUDEDEFAULT BIT = 0;
DECLARE @ASSIGNEDPROJECTSONLY BIT = 0;


SELECT DISTINCT DBO.[OSUSR_PIF_CLIENT_T5939].[ID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[ADDITIONALEMAILADDRESSES],
                DBO.[OSUSR_PIF_CLIENT_T5939].[BILLINGINCREMENT],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTCATEGORYID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTSUBCATEGORYID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTNAME],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTSTATUSID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTTYPEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLOSEDDATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CURRENCY],
                DBO.[OSUSR_PIF_CLIENT_T5939].[EXPENSETAXRATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[EXPENSETAX2RATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[FIRMCONTACTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[FLEXIBLETEMPLATEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[GRACEPERIOD],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASBILLINGINCREMENTOVERRIDE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASDEFAULTAUTOMAIL],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASDEFAULTEMAIL],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASDEFAULTPRINT],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASDEFAULTPORTAL],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASINTERESTCALC],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASLEDES3CHARCOUNTRY],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASPAYMENTMETHODONFILE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASTAXOVERRIDEEXPENSE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASTAXOVERRIDETIME],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASTAX2OVERRIDEEXPENSE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASTAX2OVERRIDETIME],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INTERESTRATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INTERESTTYPEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INVOICEACCOUNTGROUPID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INVOICENAME],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INVOICESETTINGID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LASTSTATEMENTDATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LASTUPDATEDBY],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LASTUPDATEDDATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESACCOUNTTYPEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESCLIENTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESCLIENTTAXID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESINVOICECURRENCYID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESLINEITEMTAXTYPE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESTAXCURRENCYID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[NEXTPROJECTIDENTIFIER],
                DBO.[OSUSR_PIF_CLIENT_T5939].[OPENDATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[OPERATINGBANKACCOUNTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[PAYMENTACCOUNTGROUPID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[PAYMENTROUTINGOPTIONID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[PAYMENTTERMID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[PAYMENTTERMS],
                DBO.[OSUSR_PIF_CLIENT_T5939].[REPORTOUTPUTFORMATID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[RATECODEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[RATEPRECEDENCEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TAXABLESTATUSID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TIMETAXRATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TIMETAX2RATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TRUSTDEFAULTBANKACCOUNTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TRUSTDEFAULTNAME],
                (ISNULL(TCRECENTCLIENT.CLIENTID, 0) + ISNULL(ECRECENTCLIENT.CLIENTID, 0))
FROM DBO.[OSUSR_PIF_CLIENT_T5939]
         INNER JOIN DBO.[OSUSR_PIF_PROJECT_T5939] ON DBO.[OSUSR_PIF_CLIENT_T5939].[ID] =
                                                     DBO.[OSUSR_PIF_PROJECT_T5939].[CLIENTID]
    AND DBO.[OSUSR_PIF_PROJECT_T5939].[ISACTIVE] = 1
         LEFT JOIN DBO.[OSUSR_PIF_FIRMUSERPROJECTACCESS_T5939] ON DBO.[OSUSR_PIF_PROJECT_T5939].[ID] =
                                                                  DBO.[OSUSR_PIF_FIRMUSERPROJECTACCESS_T5939].[PROJECTID]
    AND DBO.[OSUSR_PIF_FIRMUSERPROJECTACCESS_T5939].[FIRMUSERID] = @FIRMUSERID
         LEFT JOIN (SELECT DISTINCT DBO.[OSUSR_PIF_PROJECT_T5939].[CLIENTID]
                    FROM DBO.[OSUSR_PIF_TIMECARD_T5939]
                             INNER JOIN DBO.[OSUSR_PIF_PROJECT_T5939] ON DBO.[OSUSR_PIF_PROJECT_T5939].[ID] =
                                                                         DBO.[OSUSR_PIF_TIMECARD_T5939].[PROJECTID]
                    WHERE DBO.[OSUSR_PIF_PROJECT_T5939].[ISACTIVE] = 1
                      AND DBO.[OSUSR_PIF_TIMECARD_T5939].[DATE] >= @STARTDATE
                      AND DBO.[OSUSR_PIF_TIMECARD_T5939].[FIRMUSERID] = @FIRMUSERID) TCRECENTCLIENT
                   ON DBO.[OSUSR_PIF_CLIENT_T5939].[ID] = TCRECENTCLIENT.CLIENTID
         LEFT JOIN (SELECT DISTINCT DBO.[OSUSR_PIF_PROJECT_T5939].[CLIENTID]
                    FROM DBO.[OSUSR_PIF_EXPENSECARD_T5939]
                             INNER JOIN DBO.[OSUSR_PIF_PROJECT_T5939] ON DBO.[OSUSR_PIF_PROJECT_T5939].[ID] =
                                                                         DBO.[OSUSR_PIF_EXPENSECARD_T5939].[PROJECTID]
                    WHERE DBO.[OSUSR_PIF_PROJECT_T5939].[ISACTIVE] = 1
                      AND DBO.[OSUSR_PIF_EXPENSECARD_T5939].[DATE] >= @STARTDATE
                      AND DBO.[OSUSR_PIF_EXPENSECARD_T5939].[FIRMUSERID] = @FIRMUSERID) ECRECENTCLIENT
                   ON DBO.[OSUSR_PIF_CLIENT_T5939].[ID] = ECRECENTCLIENT.CLIENTID
WHERE DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTSTATUSID] = @CLIENTSTATUSACTIVE
  AND ((ISNULL(TCRECENTCLIENT.CLIENTID, 0) + ISNULL(ECRECENTCLIENT.CLIENTID, 0)) > 0 OR @INCLUDEDEFAULT = 1 OR
       DBO.[OSUSR_PIF_PROJECT_T5939].[ISDEFAULT] = 0)
  AND (@ASSIGNEDPROJECTSONLY = 0 OR DBO.[OSUSR_PIF_FIRMUSERPROJECTACCESS_T5939].[FIRMUSERID] = @FIRMUSERID)
ORDER BY DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTNAME]


-----------------------------------------------Matias------
USE PRODUCTION;
DECLARE @FIRMUSERID INT = 67794
    , @STARTDATE DATE = '19000101'
    , @CLIENTSTATUSACTIVE INT = 2
    , @INCLUDEDEFAULT BIT = 0
    , @ASSIGNEDPROJECTSONLY BIT = 0;

IF OBJECT_ID('tempdb..#temp_TCRECENTCLIENT') IS NOT NULL
    DROP TABLE #TEMP_TCRECENTCLIENT

SELECT DISTINCT DBO.[OSUSR_PIF_PROJECT_T5939].[CLIENTID]
INTO #TEMP_TCRECENTCLIENT
FROM DBO.[OSUSR_PIF_TIMECARD_T5939]
         INNER JOIN DBO.[OSUSR_PIF_PROJECT_T5939] ON DBO.[OSUSR_PIF_PROJECT_T5939].[ID] =
                                                     DBO.[OSUSR_PIF_TIMECARD_T5939].[PROJECTID]
WHERE DBO.[OSUSR_PIF_PROJECT_T5939].[ISACTIVE] = 1
  AND DBO.[OSUSR_PIF_TIMECARD_T5939].[DATE] >= @STARTDATE
  AND DBO.[OSUSR_PIF_TIMECARD_T5939].[FIRMUSERID] = @FIRMUSERID


IF OBJECT_ID('tempdb..#temp_eCRECENTCLIENT') IS NOT NULL
    DROP TABLE #TEMP_ECRECENTCLIENT

SELECT DISTINCT DBO.[OSUSR_PIF_PROJECT_T5939].[CLIENTID]
INTO #TEMP_ECRECENTCLIENT
FROM DBO.[OSUSR_PIF_EXPENSECARD_T5939]
         INNER JOIN DBO.[OSUSR_PIF_PROJECT_T5939] ON DBO.[OSUSR_PIF_PROJECT_T5939].[ID] =
                                                     DBO.[OSUSR_PIF_EXPENSECARD_T5939].[PROJECTID]
WHERE DBO.[OSUSR_PIF_PROJECT_T5939].[ISACTIVE] = 1
  AND DBO.[OSUSR_PIF_EXPENSECARD_T5939].[DATE] >= @STARTDATE
  AND DBO.[OSUSR_PIF_EXPENSECARD_T5939].[FIRMUSERID] = @FIRMUSERID


SELECT DISTINCT DBO.[OSUSR_PIF_CLIENT_T5939].[ID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[ADDITIONALEMAILADDRESSES],
                DBO.[OSUSR_PIF_CLIENT_T5939].[BILLINGINCREMENT],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTCATEGORYID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTSUBCATEGORYID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTNAME],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTSTATUSID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTTYPEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CLOSEDDATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[CURRENCY],
                DBO.[OSUSR_PIF_CLIENT_T5939].[EXPENSETAXRATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[EXPENSETAX2RATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[FIRMCONTACTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[FLEXIBLETEMPLATEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[GRACEPERIOD],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASBILLINGINCREMENTOVERRIDE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASDEFAULTAUTOMAIL],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASDEFAULTEMAIL],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASDEFAULTPRINT],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASDEFAULTPORTAL],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASINTERESTCALC],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASLEDES3CHARCOUNTRY],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASPAYMENTMETHODONFILE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASTAXOVERRIDEEXPENSE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASTAXOVERRIDETIME],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASTAX2OVERRIDEEXPENSE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[HASTAX2OVERRIDETIME],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INTERESTRATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INTERESTTYPEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INVOICEACCOUNTGROUPID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INVOICENAME],
                DBO.[OSUSR_PIF_CLIENT_T5939].[INVOICESETTINGID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LASTSTATEMENTDATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LASTUPDATEDBY],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LASTUPDATEDDATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESACCOUNTTYPEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESCLIENTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESCLIENTTAXID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESINVOICECURRENCYID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESLINEITEMTAXTYPE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[LEDESTAXCURRENCYID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[NEXTPROJECTIDENTIFIER],
                DBO.[OSUSR_PIF_CLIENT_T5939].[OPENDATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[OPERATINGBANKACCOUNTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[PAYMENTACCOUNTGROUPID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[PAYMENTROUTINGOPTIONID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[PAYMENTTERMID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[PAYMENTTERMS],
                DBO.[OSUSR_PIF_CLIENT_T5939].[REPORTOUTPUTFORMATID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[RATECODEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[RATEPRECEDENCEID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TAXABLESTATUSID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TIMETAXRATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TIMETAX2RATE],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TRUSTDEFAULTBANKACCOUNTID],
                DBO.[OSUSR_PIF_CLIENT_T5939].[TRUSTDEFAULTNAME],
                (ISNULL(TCRECENTCLIENT.CLIENTID, 0) + ISNULL(ECRECENTCLIENT.CLIENTID, 0))
FROM DBO.[OSUSR_PIF_CLIENT_T5939]
         INNER JOIN DBO.[OSUSR_PIF_PROJECT_T5939] ON DBO.[OSUSR_PIF_CLIENT_T5939].[ID] =
                                                     DBO.[OSUSR_PIF_PROJECT_T5939].[CLIENTID]
    AND DBO.[OSUSR_PIF_PROJECT_T5939].[ISACTIVE] = 1
         LEFT JOIN DBO.[OSUSR_PIF_FIRMUSERPROJECTACCESS_T5939] ON DBO.[OSUSR_PIF_PROJECT_T5939].[ID] =
                                                                  DBO.[OSUSR_PIF_FIRMUSERPROJECTACCESS_T5939].[PROJECTID]
    AND DBO.[OSUSR_PIF_FIRMUSERPROJECTACCESS_T5939].[FIRMUSERID] = @FIRMUSERID
         LEFT JOIN #TEMP_TCRECENTCLIENT TCRECENTCLIENT ON DBO.[OSUSR_PIF_CLIENT_T5939].[ID] = TCRECENTCLIENT.CLIENTID
         LEFT JOIN #TEMP_ECRECENTCLIENT ECRECENTCLIENT ON DBO.[OSUSR_PIF_CLIENT_T5939].[ID] = ECRECENTCLIENT.CLIENTID

WHERE DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTSTATUSID] = @CLIENTSTATUSACTIVE
  AND ((TCRECENTCLIENT.CLIENTID IS NOT NULL OR ECRECENTCLIENT.CLIENTID IS NOT NULL) OR @INCLUDEDEFAULT = 1 OR
       DBO.[OSUSR_PIF_PROJECT_T5939].[ISDEFAULT] = 0)
  AND (@ASSIGNEDPROJECTSONLY = 0 OR DBO.[OSUSR_PIF_FIRMUSERPROJECTACCESS_T5939].[FIRMUSERID] = @FIRMUSERID)
ORDER BY DBO.[OSUSR_PIF_CLIENT_T5939].[CLIENTNAME]
