SELECT CASE
           WHEN ('DentalBenefit' = 'LongTermDisabilityBenefit')
               THEN [ENM2I_GROUPBENEFIT].[LTDPROVISION]
           WHEN ('DentalBenefit' = 'DependentLifeBenefit')
               THEN [ENM2I_GROUPBENEFIT].[DEPLIFEPROVISION]
           WHEN ('DentalBenefit' = 'OptionalCriticalIllnessBenefit')
               THEN [ENM2I_GROUPBENEFIT].[OPTCIPROVISION]
           WHEN ('DentalBenefit' = 'DentalBenefit')
               THEN [ENM2I_GROUPBENEFIT].[DENTALPROVISION]
           WHEN ('DentalBenefit' = 'OptionalLifeBenefit')
               THEN [ENM2I_GROUPBENEFIT].[OPTMEMBERLIFEPROVISION]
           WHEN ('DentalBenefit' = 'BasicLifeBenefit')
               THEN [ENM2I_GROUPBENEFIT].[BASICLIFEPROVISION]
           WHEN ('DentalBenefit' = 'BasicADDBenefit')
               THEN [ENM2I_GROUPBENEFIT].[ADDPROVISION]
           WHEN ('DentalBenefit' = 'OptionalADDBenefit')
               THEN [ENM2I_GROUPBENEFIT].[OPTADDPROVISION]
           WHEN ('DentalBenefit' = 'CriticalIllnessBenefit')
               THEN [ENM2I_GROUPBENEFIT].[CIPROVISION]
           ELSE [ENM2I_GROUPBENEFIT].[STDPROVISION]
           END [PROVISION]
FROM [OSDATA].DBO.[OSUSR_2N1_GROUPBENEFIT] [ENM2I_GROUPBENEFIT]
WHERE ([ENM2I_GROUPBENEFIT].[M2IBATCHID] = 2)
  AND ([ENM2I_GROUPBENEFIT].[CONSOLIDATIONCODE] = 'PN_55830')
  AND LEN(
              CASE
                  WHEN ('DentalBenefit' = 'LongTermDisabilityBenefit') THEN [ENM2I_GROUPBENEFIT].[LTDPROVISION]
                  WHEN ('DentalBenefit' = 'DependentLifeBenefit') THEN [ENM2I_GROUPBENEFIT].[DEPLIFEPROVISION]
                  WHEN ('DentalBenefit' = 'OptionalCriticalIllnessBenefit')
                      THEN [ENM2I_GROUPBENEFIT].[OPTCIPROVISION]
                  WHEN ('DentalBenefit' = 'DentalBenefit')
                      THEN [ENM2I_GROUPBENEFIT].[DENTALPROVISION]
                  WHEN ('DentalBenefit' = 'OptionalLifeBenefit')
                      THEN [ENM2I_GROUPBENEFIT].[OPTMEMBERLIFEPROVISION]
                  WHEN ('DentalBenefit' = 'BasicLifeBenefit')
                      THEN [ENM2I_GROUPBENEFIT].[BASICLIFEPROVISION]
                  WHEN ('DentalBenefit' = 'BasicADDBenefit')
                      THEN [ENM2I_GROUPBENEFIT].[ADDPROVISION]
                  WHEN ('DentalBenefit' = 'OptionalADDBenefit')
                      THEN [ENM2I_GROUPBENEFIT].[OPTADDPROVISION]
                  WHEN ('DentalBenefit' = 'CriticalIllnessBenefit')
                      THEN [ENM2I_GROUPBENEFIT].[CIPROVISION]
                  ELSE [ENM2I_GROUPBENEFIT].[STDPROVISION]
                  END) <> 0


SELECT DISTINCT DIVISION, DIVISIONSIC, DIVISIONEFFECTIVEDATE, DIVISIONPROVINCE
FROM OSUSR_2N1_GROUPBENEFIT
WHERE M2IBATCHID = 2
  AND CONSOLIDATIONCODE = 'PN_55830'

SELECT [ENM2I_GROUPBENEFIT].[DIVISION]              [DIVISION],
       [ENM2I_GROUPBENEFIT].[DIVISIONEFFECTIVEDATE] [DIVISIONEFFECTIVEDATE],
       [ENM2I_GROUPBENEFIT].[DIVISIONPROVINCE]      [DIVISIONPROVINCE],
       [ENM2I_GROUPBENEFIT].[DIVISIONSIC]           [DIVISIONSIC]
FROM [OSDATA].DBO.[OSUSR_2N1_GROUPBENEFIT] [ENM2I_GROUPBENEFIT]
WHERE ([ENM2I_GROUPBENEFIT].[M2IBATCHID] = 2
    AND [ENM2I_GROUPBENEFIT].[CONSOLIDATIONCODE] = 'PN_55830')
GROUP BY [ENM2I_GROUPBENEFIT].[DIVISIONEFFECTIVEDATE], [ENM2I_GROUPBENEFIT].[DIVISIONPROVINCE],
         [ENM2I_GROUPBENEFIT].[DIVISION], [ENM2I_GROUPBENEFIT].[DIVISIONSIC]

SELECT DISTINCT [ENM2I_GROUPBENEFIT].[DIVISION]              [DIVISION],
                [ENM2I_GROUPBENEFIT].[DIVISIONEFFECTIVEDATE] [DIVISIONEFFECTIVEDATE],
                [ENM2I_GROUPBENEFIT].[DIVISIONPROVINCE]      [DIVISIONPROVINCE],
                [ENM2I_GROUPBENEFIT].[DIVISIONSIC]           [DIVISIONSIC]
FROM [OSDATA].DBO.[OSUSR_2N1_GROUPBENEFIT] [ENM2I_GROUPBENEFIT]
WHERE ([ENM2I_GROUPBENEFIT].[M2IBATCHID] = 2
    AND [ENM2I_GROUPBENEFIT].[CONSOLIDATIONCODE] = 'PN_55830')


SELECT [ENM2I_GROUPBENEFIT].[CLASS]            [CLASS],
       [ENM2I_GROUPBENEFIT].[CLASSDESCRIPTION] [CLASSDESCRIPTION],
       [ENM2I_GROUPBENEFIT].[PLAN]             [PLAN]
FROM [OSDATA].DBO.[OSUSR_2N1_GROUPBENEFIT] [ENM2I_GROUPBENEFIT]
WHERE ([ENM2I_GROUPBENEFIT].[M2IBATCHID] = 2)
  AND ([ENM2I_GROUPBENEFIT].[CONSOLIDATIONCODE] = 'PN_55830')
GROUP BY [ENM2I_GROUPBENEFIT].[CLASS], [ENM2I_GROUPBENEFIT].[PLAN], [ENM2I_GROUPBENEFIT].[CLASSDESCRIPTION]

SELECT DISTINCT [ENM2I_GROUPBENEFIT].[CLASS]            [CLASS],
                [ENM2I_GROUPBENEFIT].[CLASSDESCRIPTION] [CLASSDESCRIPTION],
                [ENM2I_GROUPBENEFIT].[PLAN]             [PLAN]
FROM [OSDATA].DBO.[OSUSR_2N1_GROUPBENEFIT] [ENM2I_GROUPBENEFIT]
WHERE ([ENM2I_GROUPBENEFIT].[M2IBATCHID] = 2)
  AND ([ENM2I_GROUPBENEFIT].[CONSOLIDATIONCODE] = 'PN_55830')

SELECT [ENM2I_GROUPBENEFIT].[CLASS]    [CLASS],
       [ENM2I_GROUPBENEFIT].[DIVISION] [DIVISION],
       [ENM2I_GROUPBENEFIT].[PLAN]     [PLAN]
FROM [OSDATA].DBO.[OSUSR_2N1_GROUPBENEFIT] [ENM2I_GROUPBENEFIT]
WHERE ([ENM2I_GROUPBENEFIT].[M2IBATCHID] = 2)
  AND ([ENM2I_GROUPBENEFIT].[CONSOLIDATIONCODE] = 'PN_55830')
GROUP BY [ENM2I_GROUPBENEFIT].[PLAN], [ENM2I_GROUPBENEFIT].[DIVISION], [ENM2I_GROUPBENEFIT].[CLASS]

SELECT DISTINCT [ENM2I_GROUPBENEFIT].[CLASS]    [CLASS],
                [ENM2I_GROUPBENEFIT].[DIVISION] [DIVISION],
                [ENM2I_GROUPBENEFIT].[PLAN]     [PLAN]
FROM [OSDATA].DBO.[OSUSR_2N1_GROUPBENEFIT] [ENM2I_GROUPBENEFIT]
WHERE ([ENM2I_GROUPBENEFIT].[M2IBATCHID] = 2)
  AND ([ENM2I_GROUPBENEFIT].[CONSOLIDATIONCODE] = 'PN_55830')


SELECT COUNT(*)
FROM [OSDATA].DBO.[OSUSR_2N1_GROUPBENEFIT] [ENM2I_GROUPBENEFIT]
WHERE ([ENM2I_GROUPBENEFIT].[M2IBATCHID] = (@M2IBATCHID))
  AND ([ENM2I_GROUPBENEFIT].[CONSOLIDATIONCODE] = @CONSOLIDATIONCODE)
  AND LEN(
              CASE
                  WHEN (('LongTermDisabilityBenefit' = @LABEL) AND ('LongTermDisabilityBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[LTDPROVISION]
                  WHEN (('DependentLifeBenefit' = @LABEL) AND ('DependentLifeBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[DEPLIFEPROVISION]
                  WHEN (('OptionalCriticalIllnessBenefit' = @LABEL) AND
                        ('OptionalCriticalIllnessBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[OPTCIPROVISION]
                  WHEN (('DentalBenefit' = @LABEL) AND ('DentalBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[DENTALPROVISION]
                  WHEN (('OptionalLifeBenefit' = @LABEL) AND ('OptionalLifeBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[OPTMEMBERLIFEPROVISION]
                  WHEN (('BasicLifeBenefit' = @LABEL) AND ('BasicLifeBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[BASICLIFEPROVISION]
                  WHEN (('BasicADDBenefit' = @LABEL) AND ('BasicADDBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[ADDPROVISION]
                  WHEN (('OptionalADDBenefit' = @LABEL) AND ('OptionalADDBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[OPTADDPROVISION]
                  WHEN (('CriticalIllnessBenefit' = @LABEL) AND
                        ('CriticalIllnessBenefit' IS NOT NULL))
                      THEN [ENM2I_GROUPBENEFIT].[CIPROVISION]
                  ELSE [ENM2I_GROUPBENEFIT].[STDPROVISION]
                  END) <> 0