SELECT *
FROM DBO.OSUSR_30U_OCA_MEDICALINFO_COPY

INSERT
INTO DBO.OSUSR_30U_OCA_MEDICALINFO_COPY (ID, MEDICALINFO_JSON)
SELECT ID, MEDICALINFO
FROM OSUSR_30U_OCA_MEDICALINFO

SELECT JSON.*, CONCAT(CONCAT(P.FIRSTNAME, ' '), P.LASTNAME) AS FULLNAME, P.OCAAPPLICATIONID
FROM (SELECT C.ID                                           AS APPLICATIONID,
             CAST(JSON_VALUE(J.VALUE, '$.PersonId') AS INT) AS PERSONID,
             JSON_VALUE(J.VALUE, '$.PersonName')            AS PERSONNAME
      FROM DBO.OSUSR_30U_OCA_MEDICALINFO_COPY C
               CROSS APPLY OPENJSON(C.MEDICALINFO_JSON, '$.ConditionCategories') AS J1
               CROSS APPLY OPENJSON(J1.VALUE, '$.ConditionDetailsList') AS J
      WHERE CAST(JSON_VALUE(J.VALUE, '$.PersonId') AS INT) > 0) JSON
         INNER JOIN OSUSR_30U_OCA_PERSON P ON P.ID = JSON.PERSONID
WHERE CONCAT(CONCAT(P.FIRSTNAME, ' '), P.LASTNAME) <> JSON.PERSONNAME


