SELECT DISTINCT DBO.OSSYS_USER_T8999.[Name], DBO.OSUSR_PIF_FIRMUSER_T8999.[Id]
FROM DBO.OSSYS_USER_T8999
         INNER JOIN DBO.OSUSR_PIF_FIRMUSER_T8999 ON DBO.OSSYS_USER_T8999.[Id] = DBO.OSUSR_PIF_FIRMUSER_T8999.[UserId]
         INNER JOIN DBO.OSUSR_PIF_PROJECT_T8999
                    ON DBO.OSUSR_PIF_PROJECT_T8999.[ResponsibleTimeKeeper] = DBO.OSUSR_PIF_FIRMUSER_T8999.[Id]
         INNER JOIN DBO.OSUSR_PIF_INVOICEPROJECT_T8999
                    ON DBO.OSUSR_PIF_PROJECT_T8999.[Id] = DBO.OSUSR_PIF_INVOICEPROJECT_T8999.[ProjectId]
         INNER JOIN DBO.OSUSR_PIF_INVOICE_T8999
                    ON DBO.OSUSR_PIF_INVOICEPROJECT_T8999.[InvoiceId] = DBO.OSUSR_PIF_INVOICE_T8999.[Id] AND
                       DBO.OSUSR_PIF_INVOICE_T8999.[InvoiceStatusId] = 2
ORDER BY DBO.OSSYS_USER_T8999.[Name];

-- Matias version
SELECT DISTINCT U.[Name]
              , F.[Id]
FROM DBO.OSSYS_USER_T8999 U
         INNER JOIN DBO.OSUSR_PIF_FIRMUSER_T8999 F ON U.[Id] = F.[UserId]
WHERE EXISTS (SELECT *
              FROM DBO.OSUSR_PIF_PROJECT_T8999 P
                       INNER JOIN DBO.OSUSR_PIF_INVOICEPROJECT_T8999 IP ON P.[Id] = IP.[ProjectId]
                       INNER JOIN DBO.OSUSR_PIF_INVOICE_T8999 I ON IP.[InvoiceId] = I.[Id]
                  AND I.[InvoiceStatusId] = 2
              WHERE P.[ResponsibleTimeKeeper] = F.[Id])
ORDER BY U.[Name], F.[Id];

-- CREATE NONCLUSTERED INDEX [IDX_BURT_INVOICEPROJECT_INVID_PROJID]
-- ON [dbo].[OSUSR_PIF_INVOICEPROJECT] ([TENANT_ID])
-- INCLUDE ([INVOICEID],[PROJECTID])

-- Optimized #1
SELECT U.[Name], FU.[Id]
FROM DBO.OSSYS_USER_T8999 U
         INNER JOIN DBO.OSUSR_PIF_FIRMUSER_T8999 FU ON U.[Id] = FU.[UserId]
         INNER JOIN DBO.OSUSR_PIF_PROJECT_T8999 P ON P.[ResponsibleTimeKeeper] = FU.[Id]
         INNER JOIN DBO.OSUSR_PIF_INVOICEPROJECT_T8999 IP ON P.[Id] = IP.[ProjectId]
         INNER JOIN DBO.OSUSR_PIF_INVOICE_T8999 I ON IP.[InvoiceId] = I.[Id] AND I.[InvoiceStatusId] = 2
GROUP BY U.[Name], FU.[Id]
ORDER BY U.[Name];

--optimized #2
WITH FILTEREDINVOICES AS (SELECT [Id]
                          FROM DBO.OSUSR_PIF_INVOICE_T8999
                          WHERE [InvoiceStatusId] = 2),
     PROJECTINVOICEMAPPING AS (SELECT P.[ResponsibleTimeKeeper] AS RESPONSIBLETIMEKEEPER, IP.[InvoiceId] AS INVOICEID
                               FROM DBO.OSUSR_PIF_PROJECT_T8999 P
                                        INNER JOIN DBO.OSUSR_PIF_INVOICEPROJECT_T8999 IP ON P.[Id] = IP.[ProjectId])
SELECT U.[Name], FU.[Id]
FROM DBO.OSSYS_USER_T8999 U
         INNER JOIN DBO.OSUSR_PIF_FIRMUSER_T8999 FU ON U.[Id] = FU.[UserId]
         INNER JOIN PROJECTINVOICEMAPPING PIM ON PIM.[ResponsibleTimeKeeper] = FU.[Id]
         INNER JOIN FILTEREDINVOICES I ON PIM.[InvoiceId] = I.[Id]
GROUP BY U.[Name], FU.[Id]
ORDER BY U.[Name];

SELECT DISTINCT DBO.[OSSYS_USER_T8999].[NAME], DBO.[OSUSR_PIF_FIRMUSER_T8999].[ID]
FROM DBO.[OSSYS_USER_T8999]
         INNER JOIN DBO.[OSUSR_PIF_FIRMUSER_T8999]
                    ON DBO.[OSSYS_USER_T8999].[ID] = DBO.[OSUSR_PIF_FIRMUSER_T8999].[USERID]
WHERE EXISTS (SELECT *
              FROM DBO.[OSUSR_PIF_PROJECT_T8999]
                       INNER JOIN DBO.[OSUSR_PIF_INVOICEPROJECT_T8999]
                                  ON DBO.[OSUSR_PIF_PROJECT_T8999].[ID] =
                                     DBO.[OSUSR_PIF_INVOICEPROJECT_T8999].[PROJECTID]
                       INNER JOIN DBO.[OSUSR_PIF_INVOICE_T8999]
                                  ON DBO.[OSUSR_PIF_INVOICEPROJECT_T8999].[INVOICEID] =
                                     DBO.[OSUSR_PIF_INVOICE_T8999].ID
                                      AND
                                     DBO.[OSUSR_PIF_INVOICE_T8999].[INVOICESTATUSID] = 2
              WHERE DBO.[OSUSR_PIF_PROJECT_T8999].[RESPONSIBLETIMEKEEPER] =
                    DBO.[OSUSR_PIF_FIRMUSER_T8999].ID)
ORDER BY DBO.[OSSYS_USER_T8999].[NAME], DBO.[OSUSR_PIF_FIRMUSER_T8999].ID