CREATE PROC CRMSYNCV2_COPYADDRESSTONEWPRIMARY
AS

    SET NOCOUNT ON
    --drop Table #tmp
--drop Table #tmp1

DECLARE
    @BUSINESSPHONE UNIQUEIDENTIFIER = '3DDDB3CC-53EE-49C4-A71F-E9E257F59E49',
    @EMAIL         UNIQUEIDENTIFIER = 'EE1C85C3-CFCB-DF11-9B2A-001D60E938C6',
    @HOMEPHONE     UNIQUEIDENTIFIER = '0DA6A26B-D7BC-DF11-B00F-001D60E938C6',
    @MOBILEPHONE   UNIQUEIDENTIFIER = 'D4A2DC80-30CA-DF11-9B2A-001D60E938C6'


SELECT TOP 5 P.SBCDEPENDENTCONTACTID AS FROMCONTACTID,
             C1.ID                   AS TOCONTACTID
INTO #TMP
FROM SBCDEPENDENTPOLICIES P
         JOIN CONTACT C ON
    P.SBCDEPENDENTCONTACTID = C.ID
         JOIN CONTACTADDRESS CA ON
    C.ID = CA.CONTACTID
         JOIN SBCPOLICIES P1 ON
    P.SBCPRIMARYPOLICYID = P1.ID
         JOIN CONTACT C1 ON P1.SBCPOLICYHOLDERID = C1.ID
         LEFT JOIN
     CONTACTADDRESS CA1 ON C1.ID = CA1.CONTACTID
WHERE SBCRELATIONSHIPTOPRIMARYID = '384326C5-39E6-4427-8536-4C831632982F'
  AND CA.ID IS NOT NULL
  AND CA.ADDRESSTYPEID = '760BF68C-4B6E-DF11-B988-001D60E938C6'
  AND CA1.ID IS NULL

---- now insert the address from contactAddress
    BEGIN TRAN
INSERT CONTACTADDRESS([CreatedById], [ModifiedById], [AddressTypeId], [CountryId], [RegionId], [CityId], [Address],
                      [Zip], [Primary], [ContactId], [ProcessListeners], [SBCAddressCareOf], [SBCTerritoryId],
                      [SBCChangeLogExists])
SELECT '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       [AddressTypeId],
       [CountryId],
       [RegionId],
       [CityId],
       [Address],
       [Zip],
       [Primary],
       TOCONTACTID,
       [ProcessListeners],
       [SBCAddressCareOf],
       [SBCTerritoryId],
       0
FROM CONTACTADDRESS
         JOIN #TMP T ON
    FROMCONTACTID = CONTACTID
UPDATE C1
SET ADDRESS      = CA.ADDRESS,
    CITYID       = CA.CITYID,
    REGIONID= CA.REGIONID,
    COUNTRYID    = CA.COUNTRYID,
    ZIP          = CA.ZIP,
    MODIFIEDON   = GETUTCDATE(),
    MODIFIEDBYID = '410006E1-CA4E-4502-A9EC-E54D922D2C00'
FROM CONTACTADDRESS CA
         JOIN #TMP T ON
    T.FROMCONTACTID = CA.CONTACTID
         JOIN CONTACT C1 ON
    T.TOCONTACTID = C1.ID
    COMMIT TRAN


-- now repeat this for the ContactCommunication

SELECT P.SBCDEPENDENTCONTACTID AS FROMCONTACTID,
       C1.ID                   AS TOCONTACTID,
       CC.COMMUNICATIONTYPEID
INTO #TMP1
FROM SBCDEPENDENTPOLICIES P
         JOIN CONTACT C ON
    P.SBCDEPENDENTCONTACTID = C.ID
         JOIN CONTACTCOMMUNICATION CC ON
    C.ID = CC.CONTACTID
         JOIN SBCPOLICIES P1 ON
    P.SBCPRIMARYPOLICYID = P1.ID
         JOIN #TMP T ON T.FROMCONTACTID = C.ID
         JOIN CONTACT C1 ON P1.SBCPOLICYHOLDERID = C1.ID
         LEFT JOIN
     CONTACTCOMMUNICATION CC1 ON C1.ID = CC1.CONTACTID
WHERE SBCRELATIONSHIPTOPRIMARYID = '384326C5-39E6-4427-8536-4C831632982F'
  AND CC.ID IS NOT NULL
  AND CC.COMMUNICATIONTYPEID IN (@BUSINESSPHONE, @EMAIL, @HOMEPHONE, @MOBILEPHONE)
  AND CC1.ID IS NULL


    -- this is a little different as we need to move the email as we can only have one email in the system
-- First copy things over that can be copied
    BEGIN TRAN

-- Business Phone
INSERT [dbo].[ContactCommunication]([CreatedById], [ModifiedById], [CommunicationTypeId], [ContactId], [Position],
                                    [SocialMediaId], [SearchNumber], [ProcessListeners], [Number],
                                    [IsCreatedBySynchronization], [NonActual], [NonActualReasonId], [DateSetNonActual],
                                    [ExternalCommunicationType], [SBCColumn1PreviousEmail], [SBCDuplicationValidated])
SELECT '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       CC.COMMUNICATIONTYPEID,
       T.TOCONTACTID,
       CC.POSITION,
       CC.SOCIALMEDIAID,
       CC.SEARCHNUMBER,
       CC.PROCESSLISTENERS,
       CC.NUMBER,
       CC.ISCREATEDBYSYNCHRONIZATION,
       CC.NONACTUAL,
       CC.NONACTUALREASONID,
       CC.DATESETNONACTUAL,
       CC.EXTERNALCOMMUNICATIONTYPE,
       CC.SBCCOLUMN1PREVIOUSEMAIL,
       CC.SBCDUPLICATIONVALIDATED
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
WHERE NOT EXISTS(SELECT *
                 FROM CONTACTCOMMUNICATION
                 WHERE CONTACTID = T.TOCONTACTID AND COMMUNICATIONTYPEID = @BUSINESSPHONE)
  AND T.COMMUNICATIONTYPEID = @BUSINESSPHONE

UPDATE C1
SET PHONE        = NUMBER,
    MODIFIEDON   = GETUTCDATE(),
    MODIFIEDBYID = '410006E1-CA4E-4502-A9EC-E54D922D2C00'
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
         JOIN CONTACT C1 ON
    T.TOCONTACTID = C1.ID
WHERE T.COMMUNICATIONTYPEID = @BUSINESSPHONE

    COMMIT TRAN

    BEGIN TRAN
--HomePhone
INSERT [dbo].[ContactCommunication]([CreatedById], [ModifiedById], [CommunicationTypeId], [ContactId], [Position],
                                    [SocialMediaId], [SearchNumber], [ProcessListeners], [Number],
                                    [IsCreatedBySynchronization], [NonActual], [NonActualReasonId], [DateSetNonActual],
                                    [ExternalCommunicationType], [SBCColumn1PreviousEmail], [SBCDuplicationValidated])
SELECT '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       CC.COMMUNICATIONTYPEID,
       T.TOCONTACTID,
       CC.POSITION,
       CC.SOCIALMEDIAID,
       CC.SEARCHNUMBER,
       CC.PROCESSLISTENERS,
       CC.NUMBER,
       CC.ISCREATEDBYSYNCHRONIZATION,
       CC.NONACTUAL,
       CC.NONACTUALREASONID,
       CC.DATESETNONACTUAL,
       CC.EXTERNALCOMMUNICATIONTYPE,
       CC.SBCCOLUMN1PREVIOUSEMAIL,
       CC.SBCDUPLICATIONVALIDATED
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
WHERE NOT EXISTS(SELECT *
                 FROM CONTACTCOMMUNICATION
                 WHERE CONTACTID = T.TOCONTACTID AND COMMUNICATIONTYPEID = @HOMEPHONE)
  AND T.COMMUNICATIONTYPEID = @HOMEPHONE

UPDATE CONTACT
SET HOMEPHONE    = NUMBER,
    MODIFIEDON   = GETUTCDATE(),
    MODIFIEDBYID = '410006E1-CA4E-4502-A9EC-E54D922D2C00'
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
WHERE T.COMMUNICATIONTYPEID = @HOMEPHONE
  AND CONTACT.ID = T.TOCONTACTID

    COMMIT TRAN


    BEGIN TRAN
--MobilePHone
INSERT [dbo].[ContactCommunication]([CreatedById], [ModifiedById], [CommunicationTypeId], [ContactId], [Position],
                                    [SocialMediaId], [SearchNumber], [ProcessListeners], [Number],
                                    [IsCreatedBySynchronization], [NonActual], [NonActualReasonId], [DateSetNonActual],
                                    [ExternalCommunicationType], [SBCColumn1PreviousEmail], [SBCDuplicationValidated])
SELECT '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       CC.COMMUNICATIONTYPEID,
       T.TOCONTACTID,
       CC.POSITION,
       CC.SOCIALMEDIAID,
       CC.SEARCHNUMBER,
       CC.PROCESSLISTENERS,
       CC.NUMBER,
       CC.ISCREATEDBYSYNCHRONIZATION,
       CC.NONACTUAL,
       CC.NONACTUALREASONID,
       CC.DATESETNONACTUAL,
       CC.EXTERNALCOMMUNICATIONTYPE,
       CC.SBCCOLUMN1PREVIOUSEMAIL,
       CC.SBCDUPLICATIONVALIDATED
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
WHERE NOT EXISTS(SELECT *
                 FROM CONTACTCOMMUNICATION
                 WHERE CONTACTID = T.TOCONTACTID AND COMMUNICATIONTYPEID = @MOBILEPHONE)
  AND T.COMMUNICATIONTYPEID = @MOBILEPHONE

UPDATE C1
SET MOBILEPHONE  = NUMBER,
    MODIFIEDON   = GETUTCDATE(),
    MODIFIEDBYID = '410006E1-CA4E-4502-A9EC-E54D922D2C00'
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
         JOIN CONTACT C1 ON
    T.TOCONTACTID = C1.ID
WHERE T.COMMUNICATIONTYPEID = @MOBILEPHONE

    COMMIT TRAN


    BEGIN TRAN
-- email.  This is different as we need to move the email rather than copy
INSERT [dbo].[ContactCommunication]([CreatedById], [ModifiedById], [CommunicationTypeId], [ContactId], [Position],
                                    [SocialMediaId], [SearchNumber], [ProcessListeners], [Number],
                                    [IsCreatedBySynchronization], [NonActual], [NonActualReasonId], [DateSetNonActual],
                                    [ExternalCommunicationType], [SBCColumn1PreviousEmail], [SBCDuplicationValidated])
SELECT '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       '410006E1-CA4E-4502-A9EC-E54D922D2C00',
       CC.COMMUNICATIONTYPEID,
       T.TOCONTACTID,
       CC.POSITION,
       CC.SOCIALMEDIAID,
       CC.SEARCHNUMBER,
       CC.PROCESSLISTENERS,
       CC.NUMBER,
       CC.ISCREATEDBYSYNCHRONIZATION,
       CC.NONACTUAL,
       CC.NONACTUALREASONID,
       CC.DATESETNONACTUAL,
       CC.EXTERNALCOMMUNICATIONTYPE,
       CC.SBCCOLUMN1PREVIOUSEMAIL,
       CC.SBCDUPLICATIONVALIDATED
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
WHERE NOT EXISTS(SELECT * FROM CONTACTCOMMUNICATION WHERE CONTACTID = T.TOCONTACTID AND COMMUNICATIONTYPEID = @EMAIL)
  AND T.COMMUNICATIONTYPEID = @EMAIL

UPDATE C1
SET EMAIL        = NUMBER,
    MODIFIEDON   = GETUTCDATE(),
    MODIFIEDBYID = '410006E1-CA4E-4502-A9EC-E54D922D2C00'
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
         JOIN CONTACT C1 ON
    T.TOCONTACTID = C1.ID
WHERE T.COMMUNICATIONTYPEID = @EMAIL

    -- now delete the old email
DELETE CONTACTCOMMUNICATION
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
WHERE T.COMMUNICATIONTYPEID = @EMAIL

    -- reset the old email on the contact record
UPDATE CONTACT
SET EMAIL        = '',
    MODIFIEDON   = GETUTCDATE(),
    MODIFIEDBYID = '410006E1-CA4E-4502-A9EC-E54D922D2C00'
FROM CONTACTCOMMUNICATION CC
         JOIN #TMP1 T ON
    CC.CONTACTID = T.FROMCONTACTID AND
    CC.COMMUNICATIONTYPEID = T.COMMUNICATIONTYPEID
WHERE T.COMMUNICATIONTYPEID = @EMAIL
    COMMIT TRAN
GO

